sudo: false

os:
  - windows
  - linux

language:
  - bash
  - java

jdk:
  - oraclejdk8

install:
 - if [ "${TRAVIS_OS_NAME}" == "windows" ]; then \n
   export JAVA_HOME=${JAVA_HOME:-/c/jdk} && \n
   export PATH=${JAVA_HOME}/bin:${PATH} && \n
   choco install jdk8 -params 'installdir=c:\\jdk' -y; \n
   fi
 - ./gradlew --version

script:
  - ./gradlew --continue

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "windows" ]; then ./gradlew --stop; fi
# - if [ "${TRAVIS_OS_NAME}" == "windows" ]; then export PATH=${JAVA_HOME}/bin:${PATH}; fi
# - if [ "${TRAVIS_OS_NAME}" == "windows" ]; then choco install jdk8 -params 'installdir=c:\\jdk' -y; fi