sudo: false

os:
  - windows
  - linux

language:
  - bash
  - java

jdk:
  - oraclejdk8

install:
 - if [ "${TRAVIS_OS_NAME} == "windows" ]; then export JAVA_HOME=${JAVA_HOME:-/c/jdk}; fi
 - ./gradlew --version

script:
  - ./gradlew --continue
