sudo: false

os:
  - windows
  - linux

language:
  - bash
  - java

jdk:
  - oraclejdk8

install: >-
 - if ["$TRAVIS_OS_NAME" = "windows"]; then
    export JAVA_HOME=${JAVA_HOME:-/c/jdk};
    export PATH=${JAVA_HOME}/bin:${PATH};
    choco install jdk8 -params 'installdir=c:\\jdk' -y;
    fi
 - ./gradlew --version

script:
  - ./gradlew --continue
